name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.3
    services:
      db:
        image: mysql:5.7.27
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
